### ISSUE TITLE
Installed this plugin with latest Tabby but no docker profile showing up

### ISSUE THREAD

**Issue by roniez** [Eugeny/tabby-docker#10]
I have installed this latest plugin with latest version of tabby but i am not able to select any docker profiles. nothing is showing up under the profile list.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by wildsonc** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/72408418/145679454-fb65cddc-778d-4cdf-88ab-11574448b5bc.png)
![image](https://user-images.githubusercontent.com/72408418/145679468-7be1bc6e-648b-4ba1-8df6-6a17167322e0.png)

**Comment by Eugeny** [comment]
Is docker daemon using a named pipe or a port in your setup?

**Comment by xzclinux** [comment]
Do tabby and docker need to be running on windows to connect to docker?
Does tabby have the ability to connect to a docker container running on a subsystem?

**Comment by roniez** [comment]
Yes but you need to have docker-cli on windows.
You can install docker-cli only on windows with chocolatey

Chocolatey Software | Docker CLI 19.03.12
<https://community.chocolatey.org/packages/docker-cli>

Ronny Nordstrand
Sädgåsvägen 11
745 97 Enköping, Sweden

E-Mail: ***@***.***
Tel: +46 (0) 70 236 80 27

**Comment by Eugeny** [comment]
Done in tabby-docker 0.2.0 - you can host set Docker daemon's host and port in settings
