### ISSUE TITLE
Bug | with the docker plugin

### ISSUE THREAD

**Issue by naumcei** [Eugeny/tabby-docker#11]
Hi Guys,

Nice work with the app, there is a bug with the docker plugin

Version: 1.1.158
Docker: 0.0.2
Os: Windows 10

![image](https://user-images.githubusercontent.com/10113045/136658927-4a2cf7c2-002c-4ee6-ba0e-4f0043bf2778.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by ntctuyen** [comment]
I got the same issue today. How can we overcome this issue?

**Comment by Eugeny** [comment]
Fixed in v0.1.0
